[Definition]
failregex = ^.*"(?:client_ip|remote_ip)":"<HOST>".*"status":(?:308|400|401|403|404|405|408|429)\b.*$
            ^.*"status":(?:308|400|401|403|404|405|408|429)\b.*"(?:client_ip|remote_ip)":"<HOST>".*$
ignoreregex =
