[redqueenx-caddy-status]
enabled = true
filter = redqueenx-caddy-status
logpath = /opt/RedqueenX/runtime/docker/caddy-logs/access.log
maxretry = 30
findtime = 10m
bantime = 2h
port = http,https

[redqueenx-caddy-scan-path]
enabled = true
filter = redqueenx-caddy-scan-path
logpath = /opt/RedqueenX/runtime/docker/caddy-logs/access.log
maxretry = 4
findtime = 1h
bantime = 24h
port = http,https
